import type { Channel, State } from "./types"

const now = Date.now()
const data = [
  [
    "mei",
    "MEI",
    "东京夜行 · 一起走进霓虹里的故事",
    "Tokyo after dark. A walk through the neon.",
    "irl",
    "tokyo",
    "12.8K",
    "28.6K",
    "#e9a8fd",
    "城市漫步,夜景,一起看世界",
  ],
  [
    "kai",
    "Kai Studio",
    "今晚不加班，一起构建有趣的东西",
    "Building something worth staying up for",
    "creative",
    "desk",
    "3.2K",
    "12.4K",
    "#90cad7",
    "设计,开发,创作",
  ],
  [
    "luna",
    "Luna FM",
    "把世界调成静音，留一点爵士",
    "Late night jazz. Find your frequency.",
    "music",
    "music",
    "8.6K",
    "45.2K",
    "#efb17d",
    "爵士,放松,深夜电台",
  ],
  [
    "nova",
    "NOVA",
    "新地图开荒，来当我的队友",
    "New world. New adventures. Join the party.",
    "gaming",
    "game",
    "24.1K",
    "109K",
    "#b1a6fa",
    "游戏,冒险,多人",
  ],
  [
    "yuki",
    "Yuki",
    "山间慢生活 · 今天去看日落",
    "Chasing the last light in the mountains",
    "irl",
    "mountain",
    "2.1K",
    "9.3K",
    "#8dceab",
    "户外,旅行,摄影",
  ],
  [
    "arch",
    "ARCHIVE",
    "从一张白纸开始：视觉设计现场",
    "From blank canvas to something beautiful",
    "creative",
    "art",
    "1.4K",
    "7.8K",
    "#f4bfba",
    "插画,设计,工作流",
  ],
  [
    "river",
    "River Sessions",
    "周末不插电 · 原创音乐现场",
    "Sunday unplugged. An intimate live session.",
    "music",
    "concert",
    "0",
    "18.2K",
    "#ddb87e",
    "独立音乐,现场,会员",
  ],
  [
    "atlas",
    "Atlas",
    "冰岛环岛记 · 留给自己的风景",
    "Iceland, slowly. A film about getting lost.",
    "irl",
    "iceland",
    "0",
    "36.7K",
    "#87b5cf",
    "纪录片,回放,旅行",
  ],
] as const
export const categories = ["all", "irl", "gaming", "music", "creative"] as const
export function createState(): State {
  const channels: Channel[] = data.map((r, i) => ({
    id: r[0],
    sessionId: `seed-session-${r[0]}`,
    ownerId: i === 0 ? "creator" : `owner-${r[0]}`,
    name: r[1],
    title: r[2],
    titleEn: r[3],
    description:
      "分享值得停下来的瞬间。欢迎来到我的频道，在这里一起探索、创作和交流。",
    category: r[4],
    language: i % 3 === 0 ? "zh" : "en",
    cover: `/covers/${r[5]}.jpg`,
    avatar: r[1].slice(0, 1),
    color: r[8],
    followers: r[7],
    viewers: parseFloat(r[6]) * 1000,
    tags: r[9].split(","),
    status: i === 6 ? "scheduled" : i === 7 ? "ended" : "live",
    access: i === 6 ? "member" : i === 7 ? "ticket" : "free",
    source: {
      kind: "hls",
      url: "/media/master.m3u8",
      live: false,
      subtitles: "/media/captions.vtt",
    },
    scheduledAt: now + 86400000,
    announcement: "欢迎来到直播间。友善交流，一起享受此刻 ✨",
    slowMode: false,
    chatMode: "all",
    mutedUsers: [],
  }))
  const people = [
    ["momo", "今天的氛围也太好了"],
    ["Alvin", "The colors are incredible"],
    ["小满", "戴上耳机，沉浸式散步 🎧"],
    ["June", "从忙碌的一天里暂停一下"],
    ["Oliver", "What camera are you using?"],
    ["momo", "这个转角真的好美"],
    ["Coco", "刚下班，赶上啦"],
    ["安可", "想把这一帧设成壁纸"],
  ]
  return {
    version: 1,
    channels,
    users: [
      {
        id: "viewer",
        name: "Alex Chen",
        email: "alex@example.test",
        credits: 500,
        role: "viewer",
        follows: ["mei", "luna"],
        bookmarks: [],
        reservations: [],
        blocked: [],
        history: [],
        notifications: true,
      },
      {
        id: "creator",
        name: "MEI",
        email: "mei@example.test",
        credits: 800,
        role: "creator",
        follows: [],
        bookmarks: [],
        reservations: [],
        blocked: [],
        history: [],
        notifications: true,
      },
      {
        id: "moderator",
        name: "Room Mod",
        email: "mod@example.test",
        credits: 100,
        role: "moderator",
        follows: ["mei"],
        bookmarks: [],
        reservations: [],
        blocked: [],
        history: [],
        notifications: true,
      },
    ],
    orders: [],
    memberships: [],
    gifts: [],
    notices: [],
    messages: channels.flatMap((c, ci) =>
      people.map((p, i) => ({
        id: `seed-${c.id}-${i}`,
        roomId: c.id,
        seq: ci * 8 + i + 1,
        userId: `guest-${i}`,
        name: p[0],
        text: p[1],
        time: now - (8 - i) * 45000,
        mediaTime: i * 5,
      })),
    ),
    polls: {
      mei: {
        question: "下一站，你想去哪里？",
        options: ["京都小巷", "海边日落", "城市天台"],
        votes: {},
        closed: false,
      },
    },
    likes: {},
    reports: [],
    scenario: "normal",
    clockOffset: 0,
    seq: 64,
  }
}
